server:
  port: 8002

spring:
  application:
    name: msvc-Courses
  datasource:
    url: jdbc:mysql://localhost:3306/StudentsCourse
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
