server:
  port: 8001

spring:
  application:
    name: msvc-Students
  datasource:
    url: jdbc:postgresql://localhost:5432
    username: root
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
